{% set name = "simpervisor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7eb87ca86d5e276976f5bb0290975a05d452c6a7b7f58062daea7d8369c823c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - simpervisor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yuvipanda/simpervisor
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Simple async process supervisor
  dev_url: https://github.com/yuvipanda/simpervisor

extra:
  recipe-maintainers:
    - consideratio
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
